# Generated by Django 3.0.3 on 2020-03-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sort_str',
            field=models.CharField(default='<django.db.models.fields.related.ForeignKey>_<django.db.models.fields.related.ForeignKey>', max_length=100),
        ),
    ]
