# Generated by Django 3.0.3 on 2020-03-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='date_created',
            new_name='date_posted',
        ),
    ]
